// Generated by Wrangler on Sun Sep 15 2024 18:51:14 GMT-0500 (Colombia Standard Time)
// by running `wrangler types`

interface Env {
	GH_CLIENT_ID: string;
	GH_CLIENT_SECRET: string;
	ENV: string;
	DB: D1Database;
	API_RATELIMITER: any;
}
