name: Deploy api to cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    #   deployments: write
    name: Deploy api
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: "3.60.3"
          packageManager: bun
          command: d1 migrations apply waifu-dev-db --remote
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: "3.60.3"
          packageManager: bun
          secrets: |
            GH_CLIENT_ID
            GH_CLIENT_SECRET
          vars: |
            ENV
        env:
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          ENV: production
